blank_issues_enabled: false
contact_links:
  - name: Global Discussions
    url: https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist/discussions
    about: Please ask and answer questions here.
  - name: Blacklist Discussions
    url: https://github.com/Ultimate-Hosts-Blacklist/blacklist/discussions
    about: Please ask and answer questions related to the blacklist here.
  - name: Main Repository
    url: https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
    about: Find more information about the main repository here.
  - name: Whitelist
    url: https://github.com/Ultimate-Hosts-Blacklist/whitelist/issues
    about: Please report whitelist review requests here.
